### ISSUE TITLE
Lack of clarity for image usage when transferring code to the development server

### ISSUE THREAD

**Issue by hendyd** [limegreentangerine/c5-frontend#3]
Following my first attempt at moving my code from the local machine to the development server, quite a bit of time has been spent debugging why JS and images were not performing as expected.
As this was a relatively-known issue, I think it's best to have this documented and any 'work-arounds' put in place within the template to reduce these issues going forward.
In addition, if the changes made here are required for the `webpack` version of this builder, then can these also be brought across?

**Comment by hendyd** [comment]
#4 #5 #6 #7 are all linked to this

**Comment by prolificjones82** [comment]
All PRs merged. Thanks
